### ISSUE TITLE
new website pages - homepage, DX solutions, headless commerce, DXP commerce

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/website#646]
Please see links below for page in manager + design files

**Homepage:** 
- https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-31079c-vdg69q/7-31209c-g7qsjg
- https://www.figma.com/file/hz1HHeFPyGg7ShcSdWi0vt/ecomm?node-id=0%3A1

**DX solutions** --- THIS IS A LIVE PAGE CURRENTLY, please make sure this does not get published until complete
- https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-8294d9f1a4-c1tn1n/7-f4a3a4eaac-67zjcb
- https://www.figma.com/file/hz1HHeFPyGg7ShcSdWi0vt/ecomm?node-id=0%3A1

**Headless commerce**
- https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-b69895e8cf-p4125x/7-a2c7caf480-1bpc9z
- https://www.figma.com/file/hz1HHeFPyGg7ShcSdWi0vt/ecomm?node-id=0%3A1

**DXP commerce**
- https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-f2eed19e81-47vk87/7-a0d3d8e7a0-dml0nt
- https://www.figma.com/file/hz1HHeFPyGg7ShcSdWi0vt/ecomm

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/

https://www.zesty.io/solutions/

https://www.zesty.io/solutions/headless-cms/commerce/
