### ISSUE TITLE
new website pages - composable DXP, DAM, DXP enterprise

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/website#647]
Schema + content done for these pages, design will be added to the Figma this week. Please begin development.

**Composable DXP**
- https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-f08fb2ec8c-tk1h08/7-dcecf5c0bb-xg5qk1
- https://www.figma.com/file/T9nJAaxICoFAuuDXFgsKVK/ZESTY-PAGES-WIREFRAMES?node-id=0%3A1

**DAM**
- https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-ee91eab1ca-157tc5/7-ccd4e7c2cc-dnw6qf
- https://www.figma.com/file/T9nJAaxICoFAuuDXFgsKVK/ZESTY-PAGES-WIREFRAMES?node-id=0%3A1

**DXP enterprise**
- https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-c0e0cdc7d9-ff3h91/7-aaa092efdb-c0gvr3
- https://www.figma.com/file/T9nJAaxICoFAuuDXFgsKVK/ZESTY-PAGES-WIREFRAMES?node-id=0%3A1

**Comment by jeromeZestyIO** [comment]
DAM
https://www.zesty.io/solutions/headless-cms/digital-asset-management/

DXP enterprise
https://www.zesty.io/solutions/digital-experience-platform/dxp-enterprise/
