### ISSUE TITLE
new website page - ROI calculator

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/website#648]
Please develop this page:
https://www.figma.com/file/T9nJAaxICoFAuuDXFgsKVK/ZESTY-PAGES-WIREFRAMES?node-id=0%3A1

Page in Zesty: https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-82e1ad9d8d-c2rq2z/7-e8ebbba88f-pzq2p5

**note that the schema does not have the calculations portion included. This will need to be hardcoded. Please work with @chloespilotro to set up. We will also need to determine how to make a customized PDF to download based on their calculations.

**Comment by jomarmontuya** [comment]
@Katiemoser  @chloespilotro 

Hi All, I’m almost complete with ROI calculator I just need help how to calculate

Monthly ROI
Revenue Gained
Resources
ROI Plan
Breakdown Summary

currently I was able to get the time saved and money saved
Time saved = QA Testing + Intangibles + Standard Changes (Hours)
MoneySaved = Infrastructure + CMS setup + ongoing support + additional software + (QA Testing, Intangibles, standard changes ) whichever selected ( dev or marketer) * Hourly

please let me know if my calculations are correct

also I need more context how to use values from -> WHAT PERCENT YOU COULD ADD IN OF REVENUE?
as well as selected values from -> WHAT CMS ARE YOU CURRENTLY USING?
Thank you!
