### ISSUE TITLE
Add ZoomInfo Code to Footer

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/website#688]
Hello, can we please add this snippet to the global footer (all pages should load this): 

`      <noscript>
        <img src="https://ws.zoominfo.com/pixel/62cc55bc7b3465008f482d68" width="1" height="1" style="display: none;" alt="websights"/>
      </noscript>`

Thank you!

**Comment by jomarmontuya** [comment]
@chloespilotro  PR is up -> https://github.com/zesty-io/nextjs-website/pull/690/files

**Comment by chloespilotro** [comment]
@ardeay can you push live today please? Thank you!
